version: '3.8'

volumes:
  redis:

networks:
  db:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: secret
    volumes:
      - redis:/redis/data
    ports:
      - 6379:6379
    networks:
      - db

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    networks:
      - db
