version: '3.8'

networks:
  my_net:
    driver: bridge

services:
  conversao-distancia:
    image: fteixeiraassis/conversao-distancia:latest
    build:
      dockerfile: src/Dockerfile
      context: src
    container_name: conversao-distancia
    ports:
      - 5000:5000
    networks:
      - my_net