version: '3'
services:
  db :
    image: mariadb
    container_name: mariadb
    networks:
      - db
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: mariadbPW
      MARIADB_ROOT_PASSWORD: mariadbrootPW
    volumes:
      - "mariadb_data:/var/lib/mysql/data/"
      - "mariadb_data:/var/lib/mysql/logs/"
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db

volumes:
  mariadb_data:

networks:
  db:
    driver: bridge

