version: '3'

volumes:
  postgresdb_data:

networks:
  db:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin@123"
      POSTGRES_USER: "admin"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - db

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin@123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - db
