version: '3'

services:
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: fabianoteixeira
      ME_CONFIG_BASICAUTH_PASSWORD: DevopsPro2023!
      ME_CONFIG_MONGODB_SERVER: mongo
      #ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - mongo
    networks:
      - mongodb

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongodb:
    driver: bridge